# [mcp_servers.atlassian]
# 	type = "sse"
# 	url = "https://mcp.atlassian.com/v1/sse"

model = "gpt-5"
model_reasoning_effort = "high"
notify = ["say", "-v", "Bells", "Done!"]
preferred_auth_method = "chatgpt"
tools.web_search = true
