approval_policy = "on-request"
approvals_reviewer = "auto_review"
model = "gpt-6.1-sol"
model_reasoning_effort = "high"
personality = "none"
sandbox_mode = "workspace-write"
service_tier = "priority"
suppress_unstable_features_warning = true

[desktop]
followUpQueueMode = "steer"
mac-menu-bar-enabled = false

[desktop.open-in-target-preferences]
global = "zed"

[features]
default_mode_request_user_input = true
memories = true
multi_agent = true

[memories]
generate_memories = true
use_memories = true

[plugins."visualize@openai-bundled"]
enabled = true
