bind -n DoubleClick1Pane if -Ft = '#{==:#{pane_current_command},micro}' \
	{ send-keys -M } { resize-pane -Z -t = }

set -s command-alias[100] "unless-micro=if -F '#{==:#{pane_current_command},micro}' send-keys"

bind -n C-f unless-micro { copy-mode ; send-keys C-r }

bind -n C-n unless-micro { new-window -c '#{pane_current_path}' }

bind -n C-p unless-micro { choose-tree -sZ -O activity }
bind -n M-C-s switch-client -l

bind -n M-Left unless-micro { previous-window }
bind -n M-Right unless-micro { next-window }

bind -n M-S-Left unless-micro { run -C 'swap-window -d -s #{window_id} -t -1' }
bind -n M-S-Right unless-micro { run -C 'swap-window -d -s #{window_id} -t +1' }

bind h split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

bind p command-prompt -p 'Save as:' -I \
	'/tmp/tmux-pane-#{session_name}-#{window_index}-#{pane_index}' \
	'capture-pane -S - ; save-buffer %1 ; display "Saved as %1!"'

bind r { source-file ~/.tmux.conf ; display 'Reloaded!' }

bind s { select-pane -M ; swap-pane -s '!' }

# https://github.com/wincent/clipper
# bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'nc -N localhost 8377'
