[cursor]
	style = { shape = 'Beam', blinking = 'Always' }

[font]
	normal.family = 'MesloLGS NF'
	size = 14

[general]
	live_config_reload = true

[keyboard]
	bindings = [
		{ key = 'A', mods = 'Command', chars = "\u0001" },
		{ key = 'B', mods = 'Command', chars = "\u0002" },
		{ key = 'C', mods = 'Command', chars = "\u0003" },
		{ key = 'D', mods = 'Command', chars = "\u0004" },
		{ key = 'E', mods = 'Command', chars = "\u0005" },
		{ key = 'K', mods = 'Command', chars = "\u000B" },
		{ key = 'L', mods = 'Command', chars = "\u000C" },
		{ key = 'N', mods = 'Command', chars = "\u000E" },
		{ key = 'P', mods = 'Command', chars = "\u0010" },
		{ key = 'R', mods = 'Command', chars = "\u0012" },
		{ key = 'S', mods = 'Command', chars = "\u0013" },
		{ key = 'W', mods = 'Command', chars = "\u0017" },
		{ key = 'X', mods = 'Command', chars = "\u0018" },
		{ key = 'Z', mods = 'Command', chars = "\u001A" },

		{ key = 'Up'   , mods = 'Command', chars = "\u001B[1;5A" },
		{ key = 'Down' , mods = 'Command', chars = "\u001B[1;5B" },
		{ key = 'Right', mods = 'Command', chars = "\u001B[1;5C" },
		{ key = 'Left' , mods = 'Command', chars = "\u001B[1;5D" },
	]

[selection]
	save_to_clipboard = true

[window]
	option_as_alt = 'Both'
